### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by JoviDeCroock** [mjackson/rollup-plugin-url-resolve#4]
Related to my previous issue I resovled it manually for now by doing: 

```
import urlResolve from './node_modules/rollup-plugin-url-resolve/esm/rollup-plugin-url-resolve';
```

This however leads me to the next issue where rollup tries to include my input file and rollup-plugin-url-resolve throws the following:

```
[!] (Plugin at position 1 plugin) Error: Could not load C:\Users\jovid\Desktop\Vanilla-React-Application\src\index.js: Cannot load URL protocol: c:
Error: Could not load C:\Users\jovid\Desktop\Vanilla-React-Application\src\index.js: Cannot load URL protocol: c:
    at loadURL (C:\Users\jovid\Desktop\Vanilla-React-Application\rollup.config.js:153:13)
    at Object.load (C:\Users\jovid\Desktop\Vanilla-React-Application\rollup.config.js:165:20)
    at Promise.resolve.then (C:\Users\jovid\Desktop\Vanilla-React-Application\node_modules\rollup\dist\rollup.js:15679:25)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
    at internal/main/run_main_module.js:21:11
```

My rollup config:

```
import urlResolve from './node_modules/rollup-plugin-url-resolve/esm/rollup-plugin-url-resolve';
import { terser } from 'rollup-plugin-terser';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';

export default {
  input: 'src/index.js',
	output: {
		file: 'dist/bundle.js',
		format: 'esm', 
		sourcemap: true
	},
  plugins: [
    resolve(),
    urlResolve(),
    terser(),
  ]
}
```

This happens with the bare minimum as well. My project is the following: https://github.com/JoviDeCroock/Vanilla-Preact-Application

If I can help out any further let me know

**Comment by mjackson** [comment]
Thanks for the workaround, and sorry for the slow fix. Closing as a dup of #3

**Comment by YogliB** [comment]
@mjackson This is still an issue for me, and the workaround doesn't fix the problem...
