### ISSUE TITLE
"Error: cannot load URL protocol: c:" when attempting to use this from windows

### ISSUE THREAD

**Issue by mreinstein** [mjackson/rollup-plugin-url-resolve#7]
index.js:

```javascript
import clamp from 'https://cdn.skypack.dev/clamp'

console.log('clamped:', clamp(100, 0, 90))
```

rollup.config.js:
```javascript
import urlResolve from 'rollup-plugin-url-resolve'

export default {
    plugins: [
        urlResolve()
    ]
}
```

Output:
```bash
C:\Users\Mike\wwwroot\test-u>  npx rollup -c rollup.config.js --format es -o bundle.js index.js

[!] (plugin at position 1) Error: Could not load C:\Users\Mike\wwwroot\test-u\index.js: Cannot load URL protocol: c:
Error: Could not load C:\Users\Mike\wwwroot\test-u\index.js: Cannot load URL protocol: c:
    at loadURL (C:\Users\Mike\wwwroot\test-u\node_modules\rollup-plugin-url-resolve\cjs\rollup-plugin-url-resolve.js:148:13)
    at Object.load (C:\Users\Mike\wwwroot\test-u\node_modules\rollup-plugin-url-resolve\cjs\rollup-plugin-url-resolve.js:160:20)
    at Promise.resolve.then (C:\Users\Mike\AppData\Roaming\npm-cache\_npx\16376\node_modules\rollup\dist\shared\rollup.js:18718:25)


```

**Comment by mreinstein** [comment]
@mjackson have a PR for this, let me know if you'd like any changes to it. Thanks for a great module!
